import org.junit.Test;
import rx.Observable;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'luist' at '26/06/16 16:43' with Gradle 2.12
 *
 * @author luist, @date 26/06/16 16:43
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test
    public void testComposition1() {
        Observable
                .just(8, 9, 10)
                .doOnNext(i->System.out.println("A:" + i))
                .filter(i -> i % 3 > 0)
                .doOnNext(i->System.out.println("B:" + i))
                .map(i -> "#" + i * 10)
                .doOnNext(i->System.out.println("C:" + i))
                .filter(s -> s.length() < 4)
                .subscribe(System.out::println);
    }
}
