/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'luist' at '26/06/16 16:43' with Gradle 2.12
 *
 * @author luist, @date 26/06/16 16:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
